### ISSUE TITLE
Should cover event triggering

### ISSUE THREAD

**Issue by balupton** [rgrove/jquery-yui3-rosetta-stone#2]
Should cover event triggering/firing/simulating whatever, for native and custom events.

For instance http://jsfiddle.net/balupton/862Lg/ and http://jsfiddle.net/balupton/tFbum/ do not work together.

**Comment by lsmith** [comment]
jQuery blurs the line between DOM related events and functional events.  There are separate APIs for these in YUI:
node.simulate('click');

vs
node.fire('valueChange', payload);

**Comment by rgrove** [comment]
@drgath covered event simulation in cbf18704cfcf93815b21c9532e14e67c55089f45.
