### ISSUE TITLE
http://www.jsrosettastone.com/ domain has expired.

### ISSUE THREAD

**Issue by stiemannkj1** [rgrove/jquery-yui3-rosetta-stone#35]

**Comment by rgrove** [comment]
Yep, I let it expire. YUI is unmaintained and I don't see much value in continuing to maintain the rosetta stone. But if you still need it, it's here: http://rgrove.github.io/jquery-yui3-rosetta-stone/

**Comment by stiemannkj1** [comment]
Excellent! Thank you.
