### ISSUE TITLE
Setting/Getting Attributes

### ISSUE THREAD

**Issue by robsogc** [rgrove/jquery-yui3-rosetta-stone#5]
Is the YUI equivilent to .attr() getAttr() or getAttrs? Not sure if it's a typo or I am missing something in my setup.
Thanks.

**Comment by rgrove** [comment]
Whoops, that's a typo. The YUI equivalents are `getAttribute()` and `setAttribute()`, not `getAttr()` and `setAttr()`. Thanks for catching that.
